<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Hi" name="org.test.A" tests="6" failures="1" timestamp="13 Sep 2020 09:19:34 GMT" time="0.064" errors="0">
  <testcase name="tc12" time="0.000" classname="org.test.A">
    <skipped/>
  </testcase> <!-- tc12 -->
  <testcase name="tc12" time="0.000" classname="org.test.A">
    <failure type="java.lang.AssertionError" message="Assert Failure in tc22 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assert Failure in tc22 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.test.A.tc12(A.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- tc12 -->
  <testcase name="tc11" time="0.031" classname="org.test.A"/>
  <testcase name="tc12" time="0.001" classname="org.test.A">
    <skipped/>
  </testcase> <!-- tc12 -->
  <testcase name="tc13" time="0.016" classname="org.test.A"/>
  <testcase name="tc12" time="0.016" classname="org.test.A">
    <skipped/>
  </testcase> <!-- tc12 -->
</testsuite> <!-- org.test.A -->
